#define DEFAULT_VGA_THEME 1
#define DEFAULT_COLORS_INVERTED 0

#define ENABLE_TESTS 1
#define DEBUG_KEYBOARD 0
#define DEBUG_TO_UART 0
#define MANUAL_START 1

#define DEFAULT_YEAR 2026
#define DEFAULT_MONTH 4
#define DEFAULT_DAY 24
#define DEFAULT_HOUR 14
#define DEFAULT_MINUTE 30
