PATH C:\VENDOR\CWSDPMI;%PATH%
PATH C:\VENDOR\NASM;%PATH%

PATH C:\VENDOR\PERL\BIN;%PATH%
SET PERL5LIB=C:\VENDOR\PERL\LIB\PERL5

PATH C:\VENDOR\WATCOM\BINW;%PATH%
SET INCLUDE=C:\VENDOR\WATCOM\H
SET WATCOM=C:\VENDOR\WATCOM
SET EDPATH=C:\VENDOR\WATCOM\EDDAT
SET WIPFC=C:\VENDOR\WATCOM\WIPFC
