/* apps/bjack.c */
extern app_st app_blackjack;
/* apps/calc.c */
extern app_st app_calc;
/* apps/calendar.c */
extern app_st app_calendar;
/* apps/clock.c */
extern app_st app_clock;
/* apps/fcell.c */
extern app_st app_freecell;
/* apps/fonts.c */
extern app_st app_fonts;
/* apps/keys.c */
extern app_st app_keys;
/* apps/launcher.c */
extern app_st app_launcher;
/* apps/mahjong.c */
extern app_st app_mahjong;
/* apps/mines.c */
extern app_st app_mines;
/* apps/pairs.c */
extern app_st app_pairs;
/* apps/setup.c */
extern app_st app_setup;
/* apps/snake.c */
extern app_st app_snake;
/* apps/sounds.c */
extern app_st app_sounds;
/* apps/tetris.c */
extern app_st app_tetris;
