/* apps/about.c */
extern app_st app_about;
/* apps/blackjack.c */
extern app_st app_blackjack;
/* apps/calc.c */
extern app_st app_calc;
/* apps/calendar.c */
extern app_st app_calendar;
/* apps/clock.c */
extern app_st app_clock;
/* apps/fonts.c */
extern app_st app_fonts;
/* apps/launcher.c */
extern app_st app_launcher;
/* apps/mines.c */
extern app_st app_mines;
/* apps/pairs.c */
extern app_st app_pairs;
/* apps/patterns.c */
extern app_st app_patterns;
/* apps/snake.c */
extern uint8_t cell_colors[4];
extern app_st app_snake;
/* apps/sounds.c */
extern app_st app_sounds;
/* apps/tetris.c */
extern app_st app_tetris;
